// Traduzioni in italiano per la guida esterna @bryllim/workout-guide.
// La libreria è in inglese: qui traduciamo nomi, attrezzatura, muscoli e tipo
// esercizio così è comprensibile in Ghisa. Sono traduzioni "a dizionario"
// (non generate al volo), pensate per restare naturali in italiano da
// palestra piuttosto che letterali parola-per-parola.

export const EQUIPMENT_IT = {
  Barbell: "Bilanciere",
  Bench: "Panca",
  Bodyweight: "Corpo libero",
  Box: "Rialzo",
  Cable: "Cavi",
  Cardio: "Cardio",
  Chair: "Sedia",
  Doorway: "Stipite di una porta",
  Dumbbell: "Manubri",
  Kettlebell: "Kettlebell",
  Machine: "Macchina",
  Plate: "Disco",
  "Pull-up Bar": "Sbarra",
  "Resistance Band": "Elastico",
  "Stability Ball": "Fitball",
  Towel: "Asciugamano",
  Wall: "Muro",
};

export const MUSCLE_IT = {
  Adductors: "Adduttori",
  Back: "Schiena",
  Biceps: "Bicipiti",
  Calves: "Polpacci",
  Cardio: "Cardio",
  Chest: "Petto",
  Core: "Core",
  Forearms: "Avambracci",
  Glutes: "Glutei",
  Grip: "Presa",
  Groin: "Inguine",
  Hamstrings: "Femorali",
  Hips: "Anche",
  Lats: "Dorsali",
  Legs: "Gambe",
  "Lower Back": "Lombari",
  Mobility: "Mobilità",
  "Posterior Chain": "Catena posteriore",
  Quads: "Quadricipiti",
  "Rear Delts": "Deltoidi posteriori",
  Shoulders: "Spalle",
  Triceps: "Tricipiti",
  "Upper Back": "Dorso alto",
};

export const TYPE_IT = {
  weight_reps: "Peso e ripetizioni",
  bodyweight_reps: "Corpo libero",
  duration: "A tempo",
  distance_duration: "Distanza/tempo",
  assisted_bodyweight: "Corpo libero assistito",
};

// slug -> nome italiano
export const EXERCISE_NAME_IT = {
  "bench-press": "Panca piana",
  "incline-bench-press": "Panca inclinata",
  "incline-dumbbell-press": "Spinte con manubri su panca inclinata",
  "dumbbell-bench-press": "Panca piana con manubri",
  "decline-bench-press": "Panca declinata",
  "machine-chest-press": "Chest press alla macchina",
  "pec-deck": "Pec deck (croci alla macchina)",
  "cable-fly": "Croci ai cavi",
  "push-up": "Piegamenti",
  "weighted-push-up": "Piegamenti zavorrati",
  "overhead-press": "Distensioni sopra la testa",
  "seated-dumbbell-press": "Spinte con manubri da seduto",
  "arnold-press": "Arnold press",
  "lateral-raise": "Alzate laterali",
  "cable-lateral-raise": "Alzate laterali ai cavi",
  "front-raise": "Alzate frontali",
  "rear-delt-fly": "Croci inverse",
  "reverse-pec-deck": "Pec deck inverso",
  "face-pull": "Face pull (trazioni al volto)",
  "upright-row": "Tirate al mento",
  deadlift: "Stacco da terra",
  "romanian-deadlift": "Stacco rumeno",
  "barbell-row": "Rematore con bilanciere",
  "t-bar-row": "Rematore al T-bar",
  "dumbbell-bent-over-row": "Rematore con manubri busto flesso",
  "one-arm-dumbbell-row": "Rematore con manubrio a un braccio",
  "chest-supported-row": "Rematore con petto in appoggio",
  "seated-row": "Rematore al cavo da seduto",
  "machine-row": "Rematore alla macchina",
  "lat-pulldown": "Lat machine",
  "close-grip-lat-pulldown": "Lat machine presa stretta",
  "straight-arm-pulldown": "Pulldown a braccia tese",
  "pull-up": "Trazioni alla sbarra",
  "assisted-pull-up": "Trazioni assistite",
  "weighted-pull-up": "Trazioni zavorrate",
  "chin-up": "Trazioni presa supina",
  shrug: "Scrollate con bilanciere",
  squat: "Squat",
  "front-squat": "Squat frontale",
  "hack-squat": "Hack squat",
  "leg-press": "Leg press",
  "bulgarian-split-squat": "Affondo bulgaro",
  "walking-lunge": "Affondi in camminata",
  "step-up": "Step up",
  "leg-extension": "Leg extension",
  "leg-curl": "Leg curl",
  "seated-leg-curl": "Leg curl da seduto",
  "hip-thrust": "Hip thrust (spinta anche)",
  "glute-bridge": "Ponte glutei",
  "good-morning": "Good morning",
  "standing-calf-raise": "Calf raise in piedi",
  "seated-calf-raise": "Calf raise da seduto",
  "bicep-curl": "Curl per bicipiti",
  "hammer-curl": "Curl a martello",
  "preacher-curl": "Curl alla panca Scott",
  "cable-curl": "Curl ai cavi",
  "reverse-curl": "Curl inverso (presa prona)",
  "wrist-curl": "Curl per polsi",
  "tricep-pushdown": "Pushdown per tricipiti",
  "overhead-tricep-extension": "Estensioni tricipiti sopra la testa",
  "skull-crusher": "French press",
  "close-grip-bench-press": "Panca presa stretta",
  dip: "Dip alle parallele",
  "assisted-dip": "Dip assistiti",
  plank: "Plank",
  "side-plank": "Plank laterale",
  "hanging-leg-raise": "Sollevamento gambe alla sbarra",
  "cable-crunch": "Crunch ai cavi",
  "ab-wheel": "Ruota addominale",
  running: "Corsa",
  walking: "Camminata",
  cycling: "Ciclismo",
  rowing: "Vogatore (canottaggio)",
  "stair-climber": "Stepper",
  "dumbbell-fly": "Croci con manubri",
  "incline-cable-fly": "Croci ai cavi su panca inclinata",
  "decline-dumbbell-press": "Panca declinata con manubri",
  "smith-machine-bench-press": "Panca piana al multipower",
  "landmine-press": "Landmine press",
  "chest-dip": "Dip per il petto",
  "weighted-dip": "Dip zavorrati",
  "machine-shoulder-press": "Spinte spalle alla macchina",
  "standing-dumbbell-press": "Spinte con manubri in piedi",
  "push-press": "Push press",
  "machine-lateral-raise": "Alzate laterali alla macchina",
  "cable-front-raise": "Alzate frontali ai cavi",
  "plate-front-raise": "Alzate frontali con disco",
  "bent-over-rear-delt-raise": "Alzate posteriori busto flesso",
  "cable-rear-delt-fly": "Croci inverse ai cavi",
  "pendlay-row": "Pendlay row",
  "inverted-row": "Rematore inverso",
  "meadows-row": "Meadows row",
  "single-arm-cable-row": "Rematore al cavo a un braccio",
  "wide-grip-lat-pulldown": "Lat machine presa larga",
  "neutral-grip-pull-up": "Trazioni presa neutra",
  "assisted-chin-up": "Trazioni supine assistite",
  "weighted-chin-up": "Trazioni supine zavorrate",
  "rack-pull": "Rack pull (stacco parziale)",
  "back-extension": "Iperestensioni lombari",
  "dumbbell-shrug": "Scrollate con manubri",
  "goblet-squat": "Goblet squat",
  "smith-machine-squat": "Squat al multipower",
  "belt-squat": "Belt squat",
  "sumo-deadlift": "Stacco sumo",
  "trap-bar-deadlift": "Stacco con trap bar",
  "lying-leg-curl": "Leg curl sdraiato",
  "nordic-hamstring-curl": "Nordic curl",
  "single-leg-romanian-deadlift": "Stacco rumeno su una gamba",
  "reverse-lunge": "Affondo indietro",
  "split-squat": "Split squat",
  "cable-kickback": "Slanci ai cavi per glutei",
  "hip-abduction-machine": "Abduttori alla macchina",
  "single-leg-glute-bridge": "Ponte glutei su una gamba",
  "barbell-glute-bridge": "Ponte glutei con bilanciere",
  "dumbbell-glute-bridge": "Ponte glutei con manubrio",
  "dumbbell-hip-thrust": "Hip thrust con manubrio",
  "smith-machine-hip-thrust": "Hip thrust al multipower",
  "smith-machine-romanian-deadlift": "Stacco rumeno al multipower",
  "dumbbell-romanian-deadlift": "Stacco rumeno con manubri",
  "kettlebell-romanian-deadlift": "Stacco rumeno con kettlebell",
  "cable-pull-through": "Pull-through ai cavi",
  "machine-glute-kickback": "Slanci glutei alla macchina",
  "cable-standing-hip-abduction": "Abduzione anca in piedi ai cavi",
  "cable-standing-hip-adduction": "Adduzione anca in piedi ai cavi",
  "hip-adduction-machine": "Adduttori alla macchina",
  "smith-machine-bulgarian-split-squat": "Affondo bulgaro al multipower",
  "smith-machine-reverse-lunge": "Affondo indietro al multipower",
  "smith-machine-split-squat": "Split squat al multipower",
  "heel-elevated-goblet-squat": "Goblet squat con talloni rialzati",
  "dumbbell-sumo-squat": "Squat sumo con manubrio",
  "dumbbell-sumo-deadlift": "Stacco sumo con manubrio",
  "front-foot-elevated-split-squat": "Split squat con piede avanti rialzato",
  "deficit-reverse-lunge": "Affondo indietro in deficit",
  "dumbbell-lateral-lunge": "Affondo laterale con manubri",
  "dumbbell-curtsy-lunge": "Affondo incrociato con manubri",
  "landmine-squat": "Squat al landmine",
  "landmine-romanian-deadlift": "Stacco rumeno al landmine",
  "kettlebell-swing": "Kettlebell swing",
  "glute-focused-back-extension": "Iperestensioni per glutei",
  "reverse-hyperextension": "Iperestensioni inverse",
  "donkey-calf-raise": "Calf raise a busto flesso",
  "leg-press-calf-raise": "Calf raise alla leg press",
  "wall-sit": "Sedia al muro",
  "jump-squat": "Squat con salto",
  "incline-dumbbell-curl": "Curl con manubri su panca inclinata",
  "concentration-curl": "Curl di concentrazione",
  "ez-bar-curl": "Curl con bilanciere EZ",
  "spider-curl": "Spider curl",
  "rope-hammer-curl": "Curl a martello con corda",
  "drag-curl": "Drag curl",
  "rope-tricep-pushdown": "Pushdown tricipiti con corda",
  "dumbbell-skull-crusher": "French press con due manubri",
  "single-dumbbell-skullcrusher": "French press con un manubrio",
  "dumbbell-overhead-tricep-extension": "Estensioni tricipiti sopra la testa con manubrio",
  "single-arm-dumbbell-tricep-extension": "Estensioni tricipiti a un braccio con manubrio",
  "bench-dip": "Dip su panca",
  "tricep-kickback": "Slanci tricipiti (kickback)",
  "wrist-extension": "Estensioni per polsi",
  "farmer-carry": "Farmer's walk (trasporto pesi)",
  crunch: "Crunch",
  "reverse-crunch": "Crunch inverso",
  "russian-twist": "Russian twist",
  "bicycle-crunch": "Crunch bicicletta",
  "mountain-climber": "Mountain climber",
  "dead-bug": "Dead bug",
  "bird-dog": "Bird dog",
  "pallof-press": "Pallof press",
  "cable-woodchop": "Woodchop ai cavi",
  "half-kneeling-pallof-press": "Pallof press in ginocchio",
  "cable-pallof-hold": "Pallof hold ai cavi",
  "hanging-knee-raise": "Sollevamento ginocchia alla sbarra",
  "captains-chair-knee-raise": "Sollevamento ginocchia alla captain's chair",
  "decline-sit-up": "Sit-up su panca declinata",
  "weighted-crunch": "Crunch zavorrato",
  "weighted-russian-twist": "Russian twist zavorrato",
  "dumbbell-side-bend": "Flessioni laterali con manubrio",
  elliptical: "Ellittica",
  swimming: "Nuoto",
  "jump-rope": "Corda",
  "assault-bike": "Assault bike",
  skierg: "SkiErg",
  hiking: "Escursionismo",
  "treadmill-incline-walk": "Camminata in salita al tapis roulant",
  "battle-ropes": "Battle rope (corde ondulatorie)",
  "incline-push-up": "Piegamenti con mani rialzate",
  "knee-push-up": "Piegamenti sulle ginocchia",
  "wide-push-up": "Piegamenti presa larga",
  "diamond-push-up": "Piegamenti a diamante",
  "decline-push-up": "Piegamenti con piedi rialzati",
  "pike-push-up": "Piegamenti a V (pike)",
  "feet-elevated-pike-push-up": "Piegamenti a V con piedi rialzati",
  "archer-push-up": "Piegamenti arciere",
  "typewriter-push-up": "Piegamenti \"macchina da scrivere\"",
  "explosive-push-up": "Piegamenti esplosivi",
  "hindu-push-up": "Piegamenti hindu",
  "scapular-push-up": "Piegamenti scapolari",
  "push-up-shoulder-tap": "Piegamenti con tocco spalla",
  "wall-push-up": "Piegamenti al muro",
  "wall-walk": "Wall walk",
  "wall-handstand-push-up": "Verticale al muro con piegamenti",
  "handstand-push-up": "Piegamenti in verticale",
  "chair-dip": "Dip su sedia",
  "doorway-row": "Rematore allo stipite",
  "towel-row": "Rematore con asciugamano",
  "prone-y-raise": "Alzate a Y da proni",
  "prone-t-raise": "Alzate a T da proni",
  superman: "Superman",
  "superman-hold": "Superman isometrico",
  "reverse-snow-angel": "Angelo di neve inverso",
  "dead-hang": "Sospensione alla sbarra",
  "active-hang": "Sospensione attiva alla sbarra",
  "scapular-pull-up": "Trazioni scapolari",
  "negative-pull-up": "Trazioni negative",
  "commando-pull-up": "Trazioni commando",
  "l-sit-pull-up": "Trazioni con L-sit",
  "towel-pull-up": "Trazioni con asciugamano",
  "bodyweight-squat": "Squat a corpo libero",
  "pistol-squat": "Pistol squat",
  "assisted-pistol-squat": "Pistol squat assistito",
  "shrimp-squat": "Shrimp squat",
  "cossack-squat": "Cossack squat",
  "sissy-squat": "Sissy squat",
  "forward-lunge": "Affondo in avanti",
  "lateral-lunge": "Affondo laterale",
  "curtsy-lunge": "Affondo incrociato",
  "skater-squat": "Skater squat",
  "single-leg-box-squat": "Squat su box a una gamba",
  "step-down": "Step down",
  "calf-raise": "Calf raise",
  "single-leg-calf-raise": "Calf raise su una gamba",
  "glute-bridge-march": "Ponte glutei con marcia",
  "frog-pump": "Frog pump (ponte a rana)",
  "donkey-kick": "Donkey kick (slanci a quattro zampe)",
  "fire-hydrant": "Fire hydrant (slanci laterali a quattro zampe)",
  clamshell: "Clamshell (apertura anche)",
  "hip-airplane": "Hip airplane",
  "side-lying-hip-abduction": "Abduzione anca su un fianco",
  "side-lying-leg-raise": "Sollevamento gamba su un fianco",
  "lying-hamstring-walkout": "Walkout femorali da sdraiato",
  "towel-hamstring-curl": "Leg curl con asciugamano",
  "stability-ball-hamstring-curl": "Leg curl con fitball",
  "banded-glute-bridge": "Ponte glutei con elastico",
  "banded-hip-thrust": "Hip thrust con elastico",
  "banded-frog-pump": "Frog pump con elastico",
  "banded-clamshell": "Clamshell con elastico",
  "banded-lateral-walk": "Cammino laterale con elastico",
  "banded-monster-walk": "Monster walk con elastico",
  "banded-squat": "Squat con elastico",
  "banded-donkey-kick": "Donkey kick con elastico",
  "banded-fire-hydrant": "Fire hydrant con elastico",
  "banded-kickback": "Slanci glutei con elastico",
  "banded-standing-hip-abduction": "Abduzione anca in piedi con elastico",
  "banded-seated-hip-abduction": "Abduzione anca da seduto con elastico",
  "band-pull-apart": "Aperture con elastico",
  "banded-face-pull": "Face pull con elastico",
  "banded-row": "Rematore con elastico",
  "banded-lat-pulldown": "Lat machine con elastico",
  "banded-pallof-press": "Pallof press con elastico",
  "banded-woodchop": "Woodchop con elastico",
  "banded-dead-bug": "Dead bug con elastico",
  "hollow-body-hold": "Hollow body hold",
  "hollow-rock": "Hollow rock",
  "v-up": "V-up",
  "flutter-kick": "Flutter kick (battito gambe)",
  "lying-leg-raise": "Sollevamento gambe da sdraiato",
  "toe-touch": "Toe touch",
  "heel-tap": "Heel tap (tocco talloni)",
  "plank-shoulder-tap": "Plank con tocco spalla",
  "plank-jack": "Plank jack",
  "bear-plank": "Bear plank",
  "bear-crawl": "Bear crawl (cammino dell'orso)",
  "crab-walk": "Crab walk (cammino del granchio)",
  inchworm: "Inchworm (il bruco)",
  "l-sit-hold": "L-sit",
  "seated-knee-tuck": "Raccolta ginocchia da seduto",
  "side-plank-hip-dip": "Plank laterale con discesa anca",
  "copenhagen-plank": "Copenhagen plank",
  "dragon-flag": "Dragon flag",
  burpee: "Burpee",
  "half-burpee": "Mezzo burpee",
  "squat-thrust": "Squat thrust",
  "high-knees": "Ginocchia alte",
  "jumping-jack": "Jumping jack",
  "skater-hop": "Skater hop",
  "lateral-shuffle": "Shuffle laterale",
  "fast-feet": "Fast feet (passo veloce)",
  sprawl: "Sprawl",
  "seal-jack": "Seal jack",
  "cat-cow-stretch": "Stretching gatto-mucca",
  "arm-circles": "Circonduzioni delle braccia",
  "worlds-greatest-stretch": "Stretching \"world's greatest\"",
  "leg-swings-stretch": "Slanci gambe",
  "torso-twist-stretch": "Rotazioni busto",
  "doorway-chest-stretch": "Stretching petto allo stipite",
  "childs-pose": "Posizione del bambino",
  "kneeling-hip-flexor-stretch": "Stretching flessori dell'anca in ginocchio",
  "hamstring-stretch": "Stretching femorali",
  "standing-quad-stretch": "Stretching quadricipiti in piedi",
  "seated-forward-fold-stretch": "Piegamento in avanti da seduto",
  "cross-body-shoulder-stretch": "Stretching spalla incrociata",
  "wall-calf-stretch": "Stretching polpacci al muro",
  "butterfly-stretch": "Stretching a farfalla",
};

export function nameIt(exercise) {
  if (!exercise) return "";
  return EXERCISE_NAME_IT[exercise.slug] || exercise.name;
}

export function equipmentIt(value) {
  return EQUIPMENT_IT[value] || value;
}

export function muscleIt(value) {
  return MUSCLE_IT[value] || value;
}

export function typeIt(value) {
  return TYPE_IT[value] || value;
}
